# -*- coding: utf-8 -*-
"""Titanic(Kaggle).py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRR0Io42rrWlklOYYI8ybR-YjyokEXr8
"""

import pandas as pd
import numpy as np

train_df=pd.read_csv('/content/train.csv')
test_df=pd.read_csv('/content/test.csv')

train_df

# gender_df=pd.read_csv('/gender_submission.csv')

# gender_df

# del gender_df

test_df

train_df.info()

train_df.describe()

train_df.isnull().sum()

train_df.drop('Cabin',axis=1,inplace=True)

train_df

train_df['Embarked']=train_df['Embarked'].dropna()

train_df.duplicated().sum()

train_df = train_df.drop('Name', axis=1)

train_df=train_df.drop('Ticket',axis=1)

train_df

train_df

test_df.drop(['Name','PassengerId','Ticket','Cabin'],axis=1,inplace=True)

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
train_df.Sex=le.fit_transform(train_df.Sex)
test_df.Sex=le.transform(test_df.Sex)

le2=LabelEncoder()
train_df.Embarked=le2.fit_transform(train_df.Embarked)
test_df.Embarked=le2.transform(test_df.Embarked)

test_df

train_df['Age'].hist()

train_df['Age']=train_df['Age'].fillna(train_df['Age'].median())

print(type(train_df))

train_df.corr()

train_df.drop(['Fare','PassengerId'],axis=1,inplace=True)

import seaborn as sns
sns.heatmap(train_df.corr(),annot=True,cmap='Blues')

test_df

test_df.drop('Fare',axis=1,inplace=True)

test_df['Age']=test_df['Age'].fillna(test_df['Age'].median())

test_df

train_df['Age'].hist()

train_df.groupby('Sex')['Survived'].mean()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,10))
for i,col in enumerate(train_df.columns):

  plt.subplot(3,3,i+1)
  train_df[col].hist()
  plt.title(col)

plt.tight_layout()
plt.show()

train_df['FamilySize'] = train_df['SibSp'] + train_df['Parch'] + 1
test_df['FamilySize'] = test_df['SibSp'] + test_df['Parch'] + 1

train_df

train_df=train_df.drop(['SibSp','Parch'],axis=1)
test_df=test_df.drop(['SibSp','Parch'],axis=1)

train_df

test_df

from sklearn.preprocessing import StandardScaler

std=StandardScaler()
features=train_df.drop('Survived',axis=1).columns
train_df[features] = std.fit_transform(train_df[features])
test_df[features] = std.transform(test_df[features])

train_df

from sklearn.model_selection import train_test_split

X=train_df.drop('Survived',axis=1)
y=train_df['Survived']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train

X_test

from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

from sklearn.metrics import accuracy_score,confusion_matrix,ConfusionMatrixDisplay,classification_report

accuracy_score(y_test,y_pred)

cm=confusion_matrix(y_test,y_pred)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=['Öldü','Sağ qaldı'])
disp.plot(cmap='Blues')
plt.show()

cmat=classification_report(y_test,y_pred)
print(cmat)

from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier()
rf.fit(X_train,y_train)

y_pred_rf=rf.predict(X_test)

cmap=classification_report(y_test,y_pred_rf)
print(cmap)

print(accuracy_score(y_test,y_pred_rf))

from sklearn.model_selection import GridSearchCV

param_grid={'n_estimators':[100,200,300],
            'max_depth':[None,5,10,20],
            'min_samples_split':[2,5,10],
            'min_samples_leaf':[1,2,4]}


rf=RandomForestClassifier(random_state=42)

grid_search=GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    scoring='accuracy'
)


grid_search.fit(X_train,y_train)

print("Best parameters:",grid_search.best_params_)
print("Best score:",grid_search.best_score_)

best_rf = grid_search.best_estimator_
y_pred_best = best_rf.predict(X_test)

print("Validation accuracy:", accuracy_score(y_test, y_pred_best))

from xgboost import XGBClassifier

xgb=XGBClassifier()
xgb.fit(X_train,y_train)

y_pred_xgb=xgb.predict(X_test)

print(accuracy_score(y_test,y_pred_xgb))

test_df.columns

test_df_psg=pd.read_csv('/content/test.csv')['PassengerId']

test_df_psg

preds=best_rf.predict(test_df)

submission = pd.DataFrame({'PassengerId': test_df_psg, 'Survived': preds})
submission.to_csv('submission.csv', index=False)

submission.head()

from google.colab import files
files.download('submission.csv')

